<?php

use Illuminate\Database\Seeder;

class SubGerenciaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subgerencia')->insert([[
            'nombre' => 'Sub Gerencia de Contabilidad',
            'siglas'     => 'SGC',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'     => '1',
            'codigo_unico_creacion'     => 'SG1',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
                'nombre' => 'Sub Gerencia de Logistica y Abastecimiento',
                'siglas'     => 'SGLYA',
                'estado_subgerencia'     => '1',
                'nivel_jerarquico'     => '3',
                'jefe_inmediato'   => '1',
                'codigo_unico_creacion'     => 'SG2',
                'updated_at'=> "2017-11-24 15:55:32",
                'created_at'=> "2017-11-24 15:55:32",   
        ],[
                    'nombre' => 'Sub Gerencia de Tesoreria y Caja',
                    'siglas'     => 'SGLYA',
                    'estado_subgerencia'     => '1',
                    'nivel_jerarquico'     => '3',
                    'jefe_inmediato'   => '1',
                    'codigo_unico_creacion'     => 'SG3',
                    'updated_at'=> "2017-11-24 15:55:32",
                    'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Recursos Humanos',
            'siglas'     => 'SGRH',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '1',
            'codigo_unico_creacion'     => 'SG4',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Control Patrimonial y Maquinarias',
            'siglas'     => 'SGCPM',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '1',
            'codigo_unico_creacion'     => 'SG5',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Tecnologias de la Informacion',
            'siglas'     => 'SGTI',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'    => '1',
            'codigo_unico_creacion'     => 'SG6',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Recaudacion Tributario',
            'siglas'     => 'SGARCT/GAT/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '4',
            'codigo_unico_creacion'     => 'SG7',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Fiscalizacion Tributario',
            'siglas'     => 'SGFT/GAT/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '4',
            'codigo_unico_creacion'     => 'SG8',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Educacion, Cultura, Deporte Y Recreación',
            'siglas'     => 'SGECDR/GPSDH-MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '8',
            'codigo_unico_creacion'     => 'SG9',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Participación Ciudadana',
            'siglas'     => 'SGPC/GPSDH-MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '8',
            'codigo_unico_creacion'     => 'SG10',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Programas Sociales y Defensoriales',
            'siglas'     => 'SGPS/GPSDH-MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '8',
            'codigo_unico_creacion'     => 'SG11',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Inclusión Social Y Comunidades Nativas',
            'siglas'     => 'SGISCN/GPSDH-MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '8',
            'codigo_unico_creacion'     => 'SG12',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Defensoria Municipal y del Niño y Adolecente',
            'siglas'     => 'SGDMNA/GPSDH-MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '8',
            'codigo_unico_creacion'     => 'SG13',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Obras Publicas',
            'siglas'     => 'SGOP/GIDUR/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '5',
            'codigo_unico_creacion'     => 'SG14',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Pleneamiento Control Urbano y Catastro',
            'siglas'     => 'SGPCUyC/GIDUR/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '5',
            'codigo_unico_creacion'     => 'SG15',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Saneamiento Fisico Legal',
            'siglas'     => 'SGSFL/GIDUR/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '5',
            'codigo_unico_creacion'     => 'SG16',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Unidad Formuladora',
            'siglas'     => 'SGUF/GEPI/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '5',
            'codigo_unico_creacion'     => 'SG17',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Estudios Definitivos',
            'siglas'     => 'SGED/GEPI/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '5',
            'codigo_unico_creacion'     => 'SG18',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Transportes y Seguridad Vial',
            'siglas'     => 'SGTSV/GSPA/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '6',
            'codigo_unico_creacion'     => 'SG19',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Limpieza Publica y Areas Verdes',
            'siglas'     => 'SGLPAV/GSPA/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '6',
            'codigo_unico_creacion'     => 'SG20',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Gestion Ambiental',
            'siglas'     => 'SGGA/GSPA/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '6',
            'codigo_unico_creacion'     => 'SG21',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Seguridad Ciudadana',
            'siglas'     => 'SGSC/GSC/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '9',
            'codigo_unico_creacion'     => 'SG22',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Desarrollo Turistico Productivo',
            'siglas'     => 'SGDTP-GDE/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '7',
            'codigo_unico_creacion'     => 'SG23',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Comercialización y Licencias',
            'siglas'     => 'SGCL-GDE/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '7',
            'codigo_unico_creacion'     => 'SG24',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Sub Gerencia de Desarrollo Agropecuario y Forestal',
            'siglas'     => 'SGDAAF-GDE/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '7',
            'codigo_unico_creacion'     => 'SG25',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ],[
            'nombre' => 'Imagen Institucional',
            'siglas'     => 'II/MDP',
            'estado_subgerencia'     => '1',
            'nivel_jerarquico'     => '3',
            'jefe_inmediato'   => '10',
            'codigo_unico_creacion'     => 'SG26',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",   
        ]]);
    }
}
