<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([[
            'username' => 'administrador',
            'persona_id' => '1',
            'email'     => 'admin@gmail.com',
            'password'  => bcrypt('admin'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'nhuaman',
            'persona_id' => '2',
            'email'     => 'nhuamancerva@gmail.com',
            'password'  => bcrypt('12345678'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'administracion',
            'persona_id' => '3',
            'email'     => 'david@gmail.com',
            'password'  => bcrypt('administracion'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'gerenciamunicipal',
            'persona_id' => '4',
            'email'     => 'pablo@gmail.com',
            'password'  => bcrypt('gerenciamunicipal'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'tramite',
            'persona_id' => '5',
            'email'     => 'evy@gmail.com',
            'password'  => bcrypt('tramite'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'serviciospublicos',
            'persona_id' => '7',
            'email'     => 'serviciospublicos@gmail.com',
            'password'  => bcrypt('serviciospublicos'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'procurador',
            'persona_id' => '8',
            'email'     => 'procurador@gmail.com',
            'password'  => bcrypt('procurador'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'tributaria',
            'persona_id' => '13',
            'email'     => 'tributaria@gmail.com',
            'password'  => bcrypt('tributaria'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'fiscalizacion',
            'persona_id' => '15',
            'email'     => 'fiscalizacion@gmail.com',
            'password'  => bcrypt('fiscalizacion'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'presupuesto',
            'persona_id' => '16',
            'email'     => 'presupueston@gmail.com',
            'password'  => bcrypt('presupuesto'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'secretariageneral',
            'persona_id' => '17',
            'email'     => 'secretariageneral@gmail.com',
            'password'  => bcrypt('secretariageneral'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'educacion',
            'persona_id' => '10',
            'email'     => 'educacion@gmail.com',
            'password'  => bcrypt('educacion'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'participacion',
            'persona_id' => '10',
            'email'     => 'participacion@gmail.com',
            'password'  => bcrypt('participacion'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'programassociales',
            'persona_id' => '11',
            'email'     => 'programassociales@gmail.com',
            'password'  => bcrypt('programassociales'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'inclusionsocial',
            'persona_id' => '11',
            'email'     => 'inclusionsocial@gmail.com',
            'password'  => bcrypt('inclusionsocial'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'defensoriamunicipal',
            'persona_id' => '12',
            'email'     => 'defensoriamunicipal@gmail.com',
            'password'  => bcrypt('defensoriamunicipal'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'infraestructura',
            'persona_id' => '18',
            'email'     => 'infraestructura@gmail.com',
            'password'  => bcrypt('infraestructura'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'obraspublicas',
            'persona_id' => '18',
            'email'     => 'obraspublicas@gmail.com',
            'password'  => bcrypt('obraspublicas'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'controlurbano',
            'persona_id' => '19',
            'email'     => 'controlurbano@gmail.com',
            'password'  => bcrypt('controlurbano'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'saneamientofisico',
            'persona_id' => '19',
            'email'     => 'saneamientofisico@gmail.com',
            'password'  => bcrypt('saneamientofisico'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'estudiosproyectos',
            'persona_id' => '20',
            'email'     => 'estudiosproyectos@gmail.com',
            'password'  => bcrypt('estudiosproyectos'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'unidadformuladora',
            'persona_id' => '21',
            'email'     => 'unidadformuladora@gmail.com',
            'password'  => bcrypt('unidadformuladora'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'estudiosdefinitivos',
            'persona_id' => '22',
            'email'     => 'estudiosdefinitivos@gmail.com',
            'password'  => bcrypt('estudiosdefinitivos'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'defensacivil',
            'persona_id' => '23',
            'email'     => 'defensacivil@gmail.com',
            'password'  => bcrypt('defensacivil'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'registrocivil',
            'persona_id' => '24',
            'email'     => 'registrocivil@gmail.com',
            'password'  => bcrypt('registrocivil'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'serviciossaneamiento',
            'persona_id' => '25',
            'email'     => 'serviciossaneamiento@gmail.com',
            'password'  => bcrypt('serviciossaneamiento'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'policiamunicipal',
            'persona_id' => '26',
            'email'     => 'policiamunicipal@gmail.com',
            'password'  => bcrypt('policiamunicipal'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'transporte',
            'persona_id' => '27',
            'email'     => 'transporte@gmail.com',
            'password'  => bcrypt('transporte'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'limpiezapublica',
            'persona_id' => '28',
            'email'     => 'limpiezapublica@gmail.com',
            'password'  => bcrypt('limpiezapublica'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'gestionambiental',
            'persona_id' => '29',
            'email'     => 'gestionambiental@gmail.com',
            'password'  => bcrypt('gestionambiental'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'controlsanitario',
            'persona_id' => '30',
            'email'     => 'controlsanitario@gmail.com',
            'password'  => bcrypt('controlsanitario'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'ulefa',
            'persona_id' => '31',
            'email'     => 'ulefa@gmail.com',
            'password'  => bcrypt('ulefa'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'seguridadciudadana',
            'persona_id' => '32',
            'email'     => 'seguridadciudadana@gmail.com',
            'password'  => bcrypt('seguridadciudadana'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'oficinaseguridad',
            'persona_id' => '33',
            'email'     => 'oficinaseguridad@gmail.com',
            'password'  => bcrypt('oficinaseguridad'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'desarrolloeconomico',
            'persona_id' => '34',
            'email'     => 'desarrolloeconomico@gmail.com',
            'password'  => bcrypt('desarrolloeconomico'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'desarrolloturistico',
            'persona_id' => '35',
            'email'     => 'desarrolloturistico@gmail.com',
            'password'  => bcrypt('desarrolloturistico'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'comercializacion',
            'persona_id' => '36',
            'email'     => 'comercializacion@gmail.com',
            'password'  => bcrypt('comercializacion'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'agropecuario',
            'persona_id' => '37',
            'email'     => 'agropecuario@gmail.com',
            'password'  => bcrypt('agropecuario'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'imageninstitucional',
            'persona_id' => '38',
            'email'     => 'imageninstitucional@gmail.com',
            'password'  => bcrypt('imageninstitucional'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'logistica',
            'persona_id' => '6',
            'email'     => 'logistica@gmail.com',
            'password'  => bcrypt('logistica'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'tesoreria',
            'persona_id' => '39',
            'email'     => 'tesoreria@gmail.com',
            'password'  => bcrypt('tesoreria'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'contabilidad',
            'persona_id' => '40',
            'email'     => 'contabilidad@gmail.com',
            'password'  => bcrypt('contabilidad'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'recursoshumanos',
            'persona_id' => '41',
            'email'     => 'recursoshumanos@gmail.com',
            'password'  => bcrypt('recursoshumanos'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ],[
            'username' => 'tecnicamunicipal',
            'persona_id' => '42',
            'email'     => 'tecnicamunicipal@gmail.com',
            'password'  => bcrypt('tecnicamunicipal'),
            'estado' => 'activado',
            'updated_at'=> "2017-11-24 15:55:32",
            'created_at'=> "2017-11-24 15:55:32",
        ]]);
    }
}
